openapi: 3.0.0
info:
  title: Note generator API
  version: 1.0.0

paths:
  /form:
    get:
      x-yc-apigateway-integration:
        bucket: ${bucket}
        type: object_storage
        object: ${form_object_key}
        service_account_id: ${sa_id}
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: 
                - name
                - url
              properties:
                name:
                  type: string
                url:
                  type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${create_function_id}
        service_account_id: ${sa_id}  

  /tasks:
    get:
      x-yc-apigateway-integration:
        bucket: ${bucket}
        type: object_storage
        object: ${tasks_object_key}
        service_account_id: ${sa_id}
  
  /ydb:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${tasks_function_id}
        service_account_id: ${sa_id}  