openapi: 3.0.0
info:
  title: Note generator API
  version: 1.0.0

paths:
  /form:
    get:
      x-yc-apigateway-integration:
        bucket: ${bucket}
        type: object_storage
        object: ${form_object_key}
        service_account_id: ${sa_id}

  /tasks:
    get:
      x-yc-apigateway-integration:
        bucket: ${bucket}
        type: object_storage
        object: ${tasks_object_key}
        service_account_id: ${sa_id}